channels:
  - conda-forge

dependencies:
  - python=3.9
  - numpy=1.19.5
  - tensorflow-gpu=2.4.1
  - wandb
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - ipykernel
  - jupyter
  - astropy
  - regions==0.5.*
  - seaborn
  - scipy