channels:
  - conda-forge
  - cta-observatory
dependencies:
  - python=3.9
  - numpy=1.19.5
  - tensorflow-gpu
  - wandb
  - pandas
  - scikit-sklearn
  - matplotlib
  - tqdm
  - ipykernel
  - jupyter
  - astropy
  - regions==0.5.*