#
# CODES:
# xyz
#   x = T/TSL
#   y = DATASET TYPE (TRAINING, VALIDATION, PVALUE) => [0,1,2]
#   z = INTEGRATION TYPE (T, TE) => [0,1]

# DATASET
# T=1 TSL=5 -- TODO
# T=1 TSL=10 -- TODO
# T=5 TSL=5 -- OK
# T=5 TSL=10 -- OK
# T=10 TSL=5 -- TODO (in progress)
# T=10 TSL=10 -- OK


################################################################################
# T=1 TSL=5
################################################################################
# TODO

################################################################################
# T=1 TSL=10
################################################################################

#### TRAINING (SIZE 10000) T INTEGRATION
200:
  id: 200
  path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_T_1_TSL_10/dataset_trials_10000_type_bkg_tobs_100/integration_t_integration_time_1_region_radius_0.2_timeseries_lenght_10
  size: 10000
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 1
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

## todo




################################################################################
# T=5 TSL=5
################################################################################

#### TRAINING (SIZE 10000) T INTEGRATION
300:
  id: 300
  path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_5_TSL_5/dataset_trials_10000_type_bkg_tobs_100/integration_t_integration_time_5_region_radius_0.2_timeseries_lenght_5
  size: 10000
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 5
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

### TRAINING (SIZE 10000) TE INTEGRATION
301:
  id: 301
  path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_5_TSL_5/dataset_trials_10000_type_bkg_tobs_100/integration_te_integration_time_5_region_radius_0.2_timeseries_lenght_5
  size: 10000
  simtype: bkg
  onset: 0
  integration_type: te
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 5
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5


#### VALIDATION (SIZE 800K+)  T INTEGRATION
310:
  id: 310
  path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_5_TSL_5/dataset_trials_861217_type_bkg_tobs_100/integration_t_integration_time_5_region_radius_0.2_timeseries_lenght_5
  size: 861199
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 5
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

#### VALIDATION (SIZE 800K+)  TE INTEGRATION

311:
  id: 311
  path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_5_TSL_5/dataset_trials_861217_type_bkg_tobs_100/integration_te_integration_time_5_region_radius_0.2_timeseries_lenght_5
  size: 861199
  simtype: bkg
  onset: 0
  integration_type: te
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 5
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

#### TEST (SIZE ?) T INTEGRATION
320:
  id: 320
  path:
  size: 861199
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 5
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5



################################################################################
# T=5 TSL=10
################################################################################

### TRAINING (SIZE 10000) T INTEGRATION
400:
  id: 400
  path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_5_TSL_10/dataset_trials_10000_type_bkg_tobs_100/integration_t_integration_time_5_region_radius_0.2_timeseries_lenght_10
  size: 10000
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

### TRAINING (SIZE 10000) TE INTEGRATION
401:
  id: 410
  path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_5_TSL_10/dataset_trials_10000_type_bkg_tobs_100/integration_te_integration_time_5_region_radius_0.2_timeseries_lenght_10
  size: 10000
  simtype: bkg
  onset: 0
  integration_type: te
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5

### VALIDATION (SIZE 800K+)  T INTEGRATION
410:
  id: 410
  path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_5_TSL_10/dataset_trials_861217_type_bkg_tobs_100/integration_t_integration_time_5_region_radius_0.2_timeseries_lenght_10
  size: 861199
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5


#### VALIDATION (SIZE 800K+)  TE INTEGRATION
411:
  id: 411
  path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_5_TSL_10/dataset_trials_861217_type_bkg_tobs_100/integration_te_integration_time_5_region_radius_0.2_timeseries_lenght_10
  size: 861207
  simtype: bkg
  onset: 0
  integration_type: te
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5


### P-VALUE T INTEGRATION
420:
  id: 420
  path: /scratch
  size: 10000000
  simtype: bkg
  onset: 0
  integration_type: t
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5


### P-VALUE TE INTEGRATION -- IN PROGRESS!
421:
  id: 421
  path: /scratch/baroncelli/AP_DATA/ap_data_bkg_T_5_TSL_10/backgrounds_10mln/integration_te_integration_time_5_region_radius_0.2_timeseries_lenght_10/
  size: 10000000
  simtype: bkg
  onset: 0
  integration_type: te
  integration_time: 5
  region_radius: 0.2
  timeseries_lenght: 10
  irf: irf_South_z40_average_LST_30m
  emin: 0.03
  emax: 1
  roi: 2.5



################################################################################
# T=10 TSL=5
################################################################################

### TRAINING (SIZE 10000) T INTEGRATION
500:
    id: 500
    path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_10_TSL_5/dataset_trials_10000_type_bkg_tobs_100/integration_t_integration_time_10_region_radius_0.2_timeseries_lenght_5
    size: 10000
    simtype: bkg
    onset: 0
    integration_type: t
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 5
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5

### TRAINING (SIZE 10000) TE INTEGRATION
501:
    id: 501
    path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_10_TSL_5/dataset_trials_10000_type_bkg_tobs_100/integration_te_integration_time_10_region_radius_0.2_timeseries_lenght_5
    size: 10000
    simtype: bkg
    onset: 0
    integration_type: te
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 5
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5

510:
  id: 510

511:
  id: 511

################################################################################
# T=10 TSL=10
################################################################################

### TRAINING (SIZE 10000) T INTEGRATION
600:
    id: 600
    path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_10_TSL_10/dataset_trials_10000_type_bkg_tobs_100/integration_t_integration_time_10_region_radius_0.2_timeseries_lenght_10
    size: 10000
    simtype: bkg
    onset: 0
    integration_type: t
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5

### TRAINING (SIZE 10000) TE INTEGRATION
601:
    id: 601
    path: /data01/homes/baroncelli/AP_DATA_10000/ap_data_bkg_T_10_TSL_10/dataset_trials_10000_type_bkg_tobs_100/integration_te_integration_time_10_region_radius_0.2_timeseries_lenght_10
    size: 861207
    simtype: bkg
    onset: 0
    integration_type: te
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5


### VALIDATION (SIZE 800K+)  T INTEGRATION
610:
    id: 610
    path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_10_TSL_10/dataset_trials_861217_type_bkg_tobs_100/integration_t_integration_time_10_region_radius_0.2_timeseries_lenght_10
    size: 861207
    simtype: bkg
    onset: 0
    integration_type: t
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5

#### VALIDATION (SIZE 800K+)  TE INTEGRATION
611:
    id: 611
    path: /data01/homes/baroncelli/AP_DATA_800k_v2/ap_data_bkg_T_10_TSL_10/dataset_trials_861217_type_bkg_tobs_100/integration_te_integration_time_10_region_radius_0.2_timeseries_lenght_10
    size: 861207
    simtype: bkg
    onset: 0
    integration_type: te
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5


#### P-VALUE T INTEGRATION
620:
    id: 612
    path: /scratch/baroncelli/AP_DATA/ap_data_bkg_T_10_TSL_10/backgrounds_10mln/integration_t_integration_time_10_region_radius_0.2_timeseries_lenght_10/
    size: 9999997
    simtype: bkg
    onset: 0
    integration_type: te
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5

#### P-VALUE TE INTEGRATION
621:
    id: 612
    path: /scratch/baroncelli/AP_DATA/ap_data_bkg_T_10_TSL_10/backgrounds_10mln/integration_te_integration_time_10_region_radius_0.2_timeseries_lenght_10/
    size: 9999997
    simtype: bkg
    onset: 0
    integration_type: te
    integration_time: 10
    region_radius: 0.2
    timeseries_lenght: 10
    irf: irf_South_z40_average_LST_30m
    emin: 0.03
    emax: 1
    roi: 2.5
