 
    setup:
        simtype: grb                      # grb -> src+bkg; bkg -> empty fields; skip -> skip sim; 
                                          # wobble -> LST-like runs (str)
        runid: run0406_ID000126           # can be all or any template (list or str) in catalog
        trials: 200                       # realisations per runid
        start_count: 100                  # starting count for seed (int)
        scalefluxfactor: 1                # scale src nominal flux by factor (float)

    simulation:
        caldb: prod3b                     # calibration database
        irf: South_z40_average_LST_30m    # istrument response function
        tobs: 1800                         # total obs time (s)
        onset: 900                        # time of bkg only a.k.a. delayed onset of burst (s)
        delay: 0                         # delayed start of observation (s) (float)
        emin: 0.03                        # simulation minimum energy (TeV)
        emax: 0.15                        # simulation maximum energy (TeV)
        roi: 2.5                          # region of interest radius (deg)
        offset: 0                      # 'gw' -> from alert; value -> otherwise (deg) (str/float)
        nruns:                        # numer of runs (of lenght=tobs) for wobble simtype (int)


    analysis:
        skypix:                       # pixel size in skymap (deg) (float)
        skyroifrac:                   # ratio between skymap axis and roi (float)
        smooth:                       # Gaussian corr. kernel rad. (deg) (float)
        maxsrc:                       # number of hotspot to search for (float)
        sgmthresh: 3                  # blind-search acc. thresh. in Gaussian sigma (float)
        usepnt: yes                   # use pointing for RA/DEC (bool)
        exposure:                     # exposure times for the analysis (s) (float)
        binned: no                    # perform binned or unbinned analysis (bool)
        blind: yes                    # requires blind-search (bool)
        tool: ctools                  # which science tool (str) 
        type: 3d                      # 1d on/off or 3d full-fov (str)


    options:
        set_ebl: True                     # uses the EBL absorbed template
        extract_data: True                # if True extracts lightcurves and spectra 
        plotsky:                      # if True generates skymap plot (bool)

    path: 
        data: /data01/home/baroncelli/phd/DATA                       # all data should be under this folder
        ebl: /data01/home/baroncelli/phd/DATA/ebl_tables/gilmore_tau_fiducial.csv
        model: /data01/home/baroncelli/phd/DATA/models
        merger: /data01/home/baroncelli/phd/DATA/mergers                     # folder of alerts (str)
        bkg: /data01/home/baroncelli/phd/DATA/models/CTAIrfBackground.xml    # file of background model (str)
        catalog: /data01/home/baroncelli/phd/DATA/templates/grb_afterglow/GammaCatalogV1.0
    
